hello: {"CalendarIdentifier": 
  {
    "BUDDHIST": "buddhist", 
    "CHINESE": "chinese", 
    "COPTIC": "coptic", 
    "DANGI": "dangi", 
    "ETHIOAA": "ethioaa", 
    "ETHIOPIC": "ethiopic", 
    "GREGORIAN": "gregory", 
    "GREGORY": "gregory", 
    "HEBREW": "hebrew", 
    "INDIAN": "indian", 
    "ISLAMIC": "islamic", 
    "ISLAMIC_CIVIL": "islamic-civil", 
    "ISLAMIC_RGSA": "islamic-rgsa", 
    "ISLAMIC_TBLA": "islamic-tbla", 
    "ISLAMIC_UMALQURA": "islamic-umalqura", 
    "ISO8601": "iso8601", 
    "JAPANESE": "japanese", 
    "PERSIAN": "persian", 
    "ROC": "roc"
  }, 
  "Weekday": 
  {"1": "SUNDAY", 
   "2": "MONDAY", 
   "3": "TUESDAY", 
   "4": "WEDNESDAY", 
   "5": "THURSDAY", 
   "6": "FRIDAY", 
   "7": "SATURDAY", 
   "FRIDAY": 6, 
   "MONDAY": 2, 
   "SATURDAY": 7, 
   "SUNDAY": 1, 
   "THURSDAY": 5, 
   "TUESDAY": 3, 
   "WEDNESDAY": 4
  }, 
  "currency": "ZAR", 
  "decimalSeparator": ",
  ", 
  "digitGroupingSeparator": " ", 
  "getCalendars": [Function getCalendars], 
  "getLocales": [Function getLocales], 
  "getLocalizationAsync": [Function getLocalizationAsync], 
  "isMetric": true, 
  "isRTL": false, 
  "isoCurrencyCodes": ["CUC", "BGN", "BHD", "VEF", "MKD", "BTN", "WST", "DJF", "XUA", "PKR", "ITL", "BRB", "SIT", "MUR", "ZMK", "DZD", "RHD", "ETB", "FJD", "SSP", "AED", "XCD", "ZRN", "LUC", "KRH", "CDF", "AZN", "CLF", "ECS", "LVR", "SDG", "MXN", "STN", "MOP", "RSD", "NIC", "ZRZ", "BRC", "XBD", "KPW", "ISK", "TWD", "SDD", "MKN", "BMD", "BYR", "CHF", "BYN", "TJS", "HRD", "MRU", "HTG", "ILP", "MTP", "RON", "YUM", "KMF", "KES", "OMR", "ESB", "UYI", "NLG", "THB", "MMK", "LVL", "XTS", "ARL", "FIM", "AON", "UYW", "TMT", "PAB", "MTL", "STD", "GHS", "MVP", "XFO", "PGK", "GNF", "ARP", "ATS", "EUR", "YER", "XEU", "LUF", "MXP", "ISJ", "SYP", "IQD", "UYP", "KRW", "EEK", "AFA", "BRZ", "SCR", "FRF", "MZE", "GIP", "JPY", "ZAL", "CVE", "GRD", "SDP", "VUV", "MDL", "YUN", "NZD", "GBP", "HUF", "XOF", "BUK", "IDR", "SRD", "KWD", "MDC", "BOV", "CLP", "BIF", "BRE", "SUR", "GWP", "XAU", "SZL", "BOL", "TRL", "BSD", "MWK", "SKK", "CLE", "COP", "INR", "BAM", "XBC", "BRR", "JOD", "LTT", "RUR", "TZS", "BEC", "BOB", "KRO", "SVC", "PYG", "VNN", "KGS", "ESA", "UAK", "SGD", "LKR", "GEK", "ECV", "USD", "DKK", "BAD", "XAG", "GHC", "DOP", "CNY", "AOK", "KZT", "ILR", "YDD", "CAD", "AOA", "CRC", "LBP", "MGA", "ARM", "SLL", "MNT", "TJR", "CHW", "VES", "LTL", "ZMW", "AFN", "MCF", "SAR", "SBD", "ZWD", "VEB", "CHE", "BZD", "USS", "EGP", "MAD", "ZAR", "CZK", "MAF", "NPR", "FKP", "XAF", "CUP", "XPT", "MRO", "LYD", "ANG", "SEK", "ALK", "MZN", "SHP", "BOP", "ESP", "MYR", "MLF", "AZM", "BRN", "GNS", "ARA", "XBA", "GMD", "ZWL", "AWG", "CNX", "TPE", "LSL", "UZS", "XBB", "HNL", "ADP", "BEF", "RWF", "XRE", "XFU", "TRY", "JMD", "BGM", "RUB", "CSD", "ARS", "UYU", "PTE", "AMD", "PLN", "ERN", "CSK", "XSU", "LAK", "XPD", "GWE", "TMM", "NIO", "BWP", "TTD", "KHR", "XDR", "MXV", "BYB", "LRD", "XXX", "BAN", "NGN", "BRL", "YUR", "COU", "DEM", "VND", "USN", "PEN", "GTQ", "CNH", "DDM", "UAH", "XPF", "HKD", "MZM", "AUD", "GQE", "ZWR", "KYD", "LUL", "QAR", "PES", "PHP", "GEL", "BBD", "CYP", "ILS", "PEI", "ALL", "MGF", "BGL", "TND", "TOP", "BND", "MVR", "NAD", "UGS", "HRK", "UGX", "ROL", "IEP", "BEL", "SOS", "GYD", "PLZ", "SRG", "IRR", "AOR", "BDT", "YUD", "BGO", "NOK"],
   "locale": "en-ZA", "locales": ["en-ZA", "en-GB", "en-AU"], 
   "region": "ZA", "timezone": "Africa/Johannesburg", "useCalendars": [Function useCalendars], "useLocales": [Function useLocales]}